version: '3'
services:
  postgres:
    image: postgres
    container_name: omni
    environment:
      POSTGRES_PASSWORD: omni
      POSTGRES_USER: omni
      POSTGRES_DB: db_omni
    ports:
      - '5433:5432'
    networks:
      - bridge
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  bridge:
    driver: bridge
